# Generated by Django 4.2.4 on 2024-02-01 10:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0030_alter_employee_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 1)),
        ),
        migrations.AlterField(
            model_name='holiday_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 1)),
        ),
        migrations.CreateModel(
            name='fin_E_Way_Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Docutment_type', models.CharField(max_length=255, null=True)),
                ('Tst', models.CharField(max_length=255, null=True)),
                ('Trans_t', models.CharField(max_length=255, null=True)),
                ('Hsn', models.CharField(max_length=255, null=True)),
                ('C_name', models.CharField(max_length=255, null=True)),
                ('C_email', models.EmailField(max_length=254, null=True)),
                ('Cba', models.CharField(max_length=255, null=True)),
                ('c_gst_type', models.CharField(max_length=255, null=True)),
                ('c_gst_number', models.CharField(max_length=255, null=True)),
                ('customer_place_supply', models.CharField(max_length=255, null=True)),
                ('billing_address', models.CharField(max_length=255, null=True)),
                ('billing_number', models.CharField(max_length=255, null=True)),
                ('Reference_no', models.IntegerField(max_length=255, null=True)),
                ('Date', models.DateField(null=True)),
                ('Transportation', models.CharField(max_length=255, null=True)),
                ('Kilometres', models.CharField(max_length=255, null=True)),
                ('Vehicle_Number', models.CharField(max_length=255, null=True)),
                ('Description', models.CharField(max_length=255, null=True)),
                ('Document', models.FileField(max_length=255, upload_to='')),
                ('Sub_Total', models.IntegerField(max_length=255, null=True)),
                ('CSGT', models.IntegerField(max_length=255, null=True)),
                ('SGST', models.IntegerField(max_length=255, null=True)),
                ('Tax_Amount', models.IntegerField(max_length=255, null=True)),
                ('Shipping_Charge', models.IntegerField(max_length=255, null=True)),
                ('Adjustment', models.IntegerField(max_length=255, null=True)),
                ('Grand_Total', models.IntegerField(max_length=255, null=True)),
                ('Customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_customers')),
            ],
        ),
    ]
